# Generated by Django 3.0.1 on 2019-12-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='discount_procent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
