# Generated by Django 3.0.1 on 2020-01-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20200106_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='deals.Brand'),
        ),
    ]
